# Generated by Django 3.2.9 on 2021-12-06 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Station", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("temperature_f", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temperature_c", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weather_condition", models.CharField(max_length=255)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cloud", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Station.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
