# Generated by Django 3.2.9 on 2021-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherData', '0002_auto_20211206_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_f',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
