# Generated by Django 3.2.9 on 2021-12-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherData", "0003_alter_weatherdata_temperature_f"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="wind_kph",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
