# Generated by Django 3.2.9 on 2021-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherData', '0004_weatherdata_wind_kph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_time',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
