# Generated by Django 3.2.6 on 2021-08-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccountsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=32)),
                ("user_email", models.CharField(max_length=256)),
                ("user_password", models.CharField(max_length=32)),
            ],
        ),
    ]
