# Generated by Django 3.2.6 on 2021-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='StationModel',
        ),
        migrations.RenameField(
            model_name='stationmodel',
            old_name='address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='stationmodel',
            old_name='address_country',
            new_name='country',
        ),
    ]
